Add tickets page
SmogHard/aviasales-demo-frontend pull request #2
Opened 2018-02-19 20:07 UTC by SmogHard

2018-02-22 20:18 UTC, evgenyrodionov commented
Поч кнопка уродская
![image](https://user-images.githubusercontent.com/775692/36562010-a287da32-1826-11e8-8f93-e8d46b7d38db.png)

2018-02-22 20:18 UTC, evgenyrodionov commented
Всё сжалось, иконки аппсторов мыльные
![image](https://user-images.githubusercontent.com/775692/36562024-b0ca237a-1826-11e8-9767-abf1fe2bec06.png)

2018-02-22 20:18 UTC, evgenyrodionov commented
Да и тут тоже сжато
![image](https://user-images.githubusercontent.com/775692/36562038-b9e3e4b4-1826-11e8-8c37-cf00b877f4e0.png)

2018-02-22 20:19 UTC, evgenyrodionov commented
И чё это)
![image](https://user-images.githubusercontent.com/775692/36562055-c39c6abc-1826-11e8-83c9-d01d216d3652.png)

2018-02-22 20:20 UTC, evgenyrodionov commented
Иконки мыльные, цена не форматируется в читаемый формат
![image](https://user-images.githubusercontent.com/775692/36562086-d8cb53bc-1826-11e8-9e6a-98981cb9fb8f.png)

2018-02-22 20:32 UTC, imevro requested changes

2018-02-22 20:32 UTC, evgenyrodionov commented on src/Header/ButtonSearch.js
> +        <Button>
как кнопка может быть в ссылке? а что тогда отработает первым? нелогично как-то

2018-02-22 20:32 UTC, evgenyrodionov commented on src/Header/MainPage.js
> +        <div className="col-xs-12 col-md-offset-1 col-md-10">
а зачем тут сетка вообще

2018-02-22 20:32 UTC, evgenyrodionov commented on src/Tickets/AirlineLogo.js
> +  if (Array.isArray(props.airline)) {
1) почему не во множ числе, если это массив
2) почему у тебя под одним пропом могут придти разные типы данных? это ужасно

2018-02-22 20:32 UTC, evgenyrodionov commented on src/Tickets/AirlineLogo.js
> +  if (Array.isArray(props.airline)) {
если там может быть только один элемент, так делай массив с одним элементом

2018-02-22 20:32 UTC, evgenyrodionov commented on src/Tickets/Flight.js
> +          {flight.type ? <Type> {flight.type} </Type> : ""}
зачем пустая строка?

2018-02-22 20:32 UTC, evgenyrodionov commented on src/Tickets/Flight.js
> +          {flight.type ? <Type> {flight.type} </Type> : ""}
да и вообще, прочти про conditional rendering

2018-02-22 20:32 UTC, evgenyrodionov commented on src/Tickets/FlightXs.js
> +    return data;
какая-то странная дичь от названия функции до её смысла. что тут вообще происходит?

2018-02-22 20:32 UTC, evgenyrodionov commented on src/Tickets/FlightXs.js
> +  const flight = props.flight;
используй object destructing

2018-02-22 20:32 UTC, evgenyrodionov commented on src/Tickets/Header.js
> +  if (info.type === "lowcost") {
читай второй урок первого этапа

2018-02-22 20:32 UTC, evgenyrodionov commented on src/Tickets/Header.js
> +  return <div />;
зачем?

2018-02-23 13:52 UTC, SmogHard commented
Теперь билд вот здесь https://build-mjriduoizo.now.sh/

2018-02-24 08:55 UTC, SmogHard commented
Новый билд https://build-tcbqdfnune.now.sh

2018-02-24 16:58 UTC, SmogHard commented
Деплой https://build-ogvgzcnwfb.now.sh

2018-02-25 13:12 UTC, evgenyrodionov commented
Скоро кнопка будет больше чем форма
![image](https://user-images.githubusercontent.com/775692/36641778-a61973d2-1a46-11e8-837c-0c35c643fe64.png)

Отступы и межстрочное расстояние уебищное
![image](https://user-images.githubusercontent.com/775692/36641781-ae32bace-1a46-11e8-9c34-9203ab4fc511.png)

2018-02-25 14:03 UTC, imevro requested changes

2018-02-25 14:03 UTC, evgenyrodionov commented on src/Common/ButtonPassenger.js
> +    this.setState({ isOpen: !this.state.isOpen });
https://medium.freecodecamp.org/functional-setstate-is-the-future-of-react-374f30401b6b

2018-02-25 14:03 UTC, evgenyrodionov commented on src/Common/Checkbox.js
> +import no_check from "./no-check.png";
unchecked мб

2018-02-25 14:03 UTC, evgenyrodionov commented on src/Common/Checkbox.js
> +   }
что с отступами

2018-02-25 14:03 UTC, evgenyrodionov commented on src/Common/Counter.js
> +    this.setState({ count: this.state.count + 1 });
https://medium.freecodecamp.org/functional-setstate-is-the-future-of-react-374f30401b6b

2018-02-25 14:03 UTC, evgenyrodionov commented on src/Common/DatePicker.js
> +    : "";
не работай с пустыми строками

2018-02-25 14:03 UTC, evgenyrodionov commented on src/Common/DatePicker.js
> +    : "";
есть null и undefined

2018-02-25 14:03 UTC, evgenyrodionov commented on src/Common/DatePicker.js
> +      this.setState({ isOpenTo: false, isOpenFrom: false });
а зачем ты дважды ставишь стейт в одном методе?

2018-02-25 14:03 UTC, evgenyrodionov commented on src/Common/DatePicker.js
> +    const cellStyle = {};
почему это сделано инлайновыми стилями, а не цссом?

2018-02-25 14:03 UTC, evgenyrodionov commented on src/Common/datepicker.css
> +  background-image: url("./datepick.png");
почему иконки в пнг?

2018-02-27 18:14 UTC, SmogHard commented
Deploy https://build-xmgfztlbal.now.sh/

2018-03-01 18:41 UTC, evgenyrodionov commented
В карточках картинки слишком жипегные плюс всё тесное какое-то

![image](https://user-images.githubusercontent.com/775692/36862888-37286f86-1d99-11e8-9345-fa5cebe2f77f.png)

2018-03-01 20:02 UTC, imevro requested changes

2018-03-01 20:02 UTC, evgenyrodionov commented on src/Common/DatePicker.js
> +    : null;
не используй тут вообще тернарник, сделай обычный иф

2018-03-01 20:02 UTC, evgenyrodionov commented on src/Common/DatePicker.js
> +      isOpenTo: true,
зачем ты используешь функциональный сетстейт, если ты не используешь предыдущий стейт?

2018-03-01 20:02 UTC, evgenyrodionov commented on src/Common/DatePicker.js
> +            <div key={i} className="Price">
класснейм? откуда взялся

2018-03-01 20:02 UTC, evgenyrodionov commented on src/Search/Tickets/data.js
>          cityTo: "Барселона",
а тут?

2018-03-01 20:02 UTC, evgenyrodionov commented on src/Search/Tickets/data.js
>          transfers: "Прямой",
а тут?

2018-03-01 20:02 UTC, evgenyrodionov commented on src/Search/Tickets/data.js
>          transfers: "CDG",
если трансферс это множ число, почему тут хранится строка, а не массив?

2018-03-01 20:02 UTC, evgenyrodionov commented on src/Search/Tickets/data.js
>          total: { hour: 4, minutes: 30 },
1) тотал что? цена?
2) храни минуты целым числом (4 часа 30 минут это 270 минут)

2018-03-03 07:36 UTC, SmogHard commented
https://build-glwcixymlc.now.sh/search билд

2018-03-04 17:43 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/36948481-940691b0-1fec-11e8-9df7-a3232b3c9100.png)
![image](https://user-images.githubusercontent.com/775692/36948490-ade67dac-1fec-11e8-81e7-27882082aafd.png)

2018-03-04 17:47 UTC, imevro requested changes

2018-03-04 17:47 UTC, evgenyrodionov commented on src/Search/Tickets/Baggage.js
> +          {baggage[0].left ? "Осталось " + baggage[0].left + " билета" : null}
а почему а) это называется baggage, если речь про билеты б) ты работаешь с индексом массива?

2018-03-04 17:47 UTC, evgenyrodionov commented on src/Search/Tickets/FlightXs.js
> +  const landing = format(new Date(flight.dateTo), "HH:MM");
для дат уместен постфикс `At`

2018-03-04 17:47 UTC, evgenyrodionov commented on src/Search/Tickets/PriceAndInfo.js
> +  let formatter = [{ style: "currency" }];
почему лет

2018-03-04 19:25 UTC, SmogHard commented
Новый деплой

https://build-gtnphljrjb.now.sh/

2018-03-07 16:56 UTC, imevro requested changes

2018-03-07 16:56 UTC, evgenyrodionov commented on src/Search/Tickets/Baggage.js
> +  const baggageWithoutSuite = props.info.baggageWithoutSuite;
используй es destructing

2018-03-07 16:56 UTC, evgenyrodionov commented on src/Search/Tickets/Baggage.js
> +          {info.ticketsLeft && "Осталось " + info.ticketsLeft + " билета"}
используй es template strings

2018-03-08 06:53 UTC, SmogHard commented
https://build-nijhwustfz.now.sh/

2018-03-09 10:04 UTC, imevro requested changes

2018-03-09 10:04 UTC, evgenyrodionov commented on src/Search/Tickets/Baggage.js
> +  const { info } = props;
ты можешь использовать прямо в аргументе функции)

`function({ info }) {}`

если нужны остальные пропы, то используй es spread operator

2018-03-09 10:21 UTC, SmogHard commented
https://build-tkiegyllfc.now.sh/

2018-03-10 12:27 UTC, imevro approved these changes

2018-08-20 07:30 UTC, merged