add work checkbox
SmogHard/aviasales-demo-frontend pull request #4
Opened 2018-03-08 19:12 UTC by SmogHard

2018-03-09 07:50 UTC, SmogHard commented
https://build-iixumteqxt.now.sh билд

2018-03-09 10:25 UTC, evgenyrodionov commented
"добавить работа чекбокс"

2018-03-09 10:33 UTC, imevro requested changes
храни стейт фильтров в родителе — избавишься от дубликатов

2018-03-09 10:33 UTC, evgenyrodionov commented on src/Common/ButtonPassenger.js
> +  return passenger + count;
что здесь происходит? не совсем понимаю

2018-03-09 10:33 UTC, evgenyrodionov commented on src/Common/ButtonPassenger.js
> +              onChange={count => this.countCheck(count)}
countCheck слабый нейминг, "количество проверить"?

2018-03-09 10:33 UTC, evgenyrodionov commented on src/Common/CityFrom.js
> +  handleCityChange = (i) => {
что такое i?

2018-03-09 10:33 UTC, evgenyrodionov commented on src/Common/CityFrom.js
> +  handleCityChange = (i) => {
если это индекс, то лучше idx

2018-03-09 10:33 UTC, evgenyrodionov commented on src/Common/Counter.js
> +    return count - 1;
а зачем возвращать

2018-03-09 10:33 UTC, evgenyrodionov commented on src/Common/Counter.js
> +      return 0;
это чё за альтерантива нулевому return?

2018-03-09 10:33 UTC, evgenyrodionov commented on src/Search/Filter/Agents.js
> +const setCheck = (filter, checked) => ({ ...filter, checked });
"установить проверку"?

2018-03-09 10:33 UTC, evgenyrodionov commented on src/Search/Filter/Agents.js
> +    filter[idx].checked = !filter[idx].checked;
нахуй мутабельность

2018-03-09 10:33 UTC, evgenyrodionov commented on src/Search/Filter/Airlines.js
> +    });
у тебя уже три раза за два файла эта функция дублируется, мб подумать как лучше с ней работать?

2018-03-10 06:29 UTC, SmogHard commented
https://build-nbifypwfjb.now.sh/

2018-03-10 13:13 UTC, imevro requested changes

2018-03-10 13:13 UTC, evgenyrodionov commented on src/Common/ChoiseCity.js
> +    abbr: 'MOV',
MOW

2018-03-10 13:13 UTC, evgenyrodionov commented on src/Common/ChoiseCity.js
> +class ChoiseCity extends Component {
что такое choise

2018-03-10 13:13 UTC, evgenyrodionov commented on src/Common/ChoiseCity.js
> +        ...prevState.to,
а зачем спред оператор? просто `from: prevState.to`

2018-03-10 13:13 UTC, evgenyrodionov commented on src/Common/CityFrom.js
> +      <ButtonAction onClick={() => handleSwap()}>
а зачем создавать функцию чтобы вызвать другую?

2018-03-10 13:13 UTC, evgenyrodionov commented on src/Common/CityFrom.js
> +        {cities.map((item, idx) => (
хуитем

2018-03-10 15:46 UTC, SmogHard commented
https://build-scjzaczags.now.sh/ билд

2018-03-13 06:41 UTC, evgenyrodionov commented
8 пассажир?

![image](https://user-images.githubusercontent.com/775692/37326340-bbe691dc-26a2-11e8-8d33-bf23558d6e90.png)

2018-03-13 06:41 UTC, evgenyrodionov commented
Слиплось
![image](https://user-images.githubusercontent.com/775692/37326343-c3a37c3c-26a2-11e8-9f79-68ffb4a4e231.png)

2018-03-13 06:42 UTC, evgenyrodionov commented
Данные не сохраняются — выбрал на главной странице Туда и Обратно, нажал на "поиск" — перешло, но всё сбросилось

2018-03-13 06:43 UTC, evgenyrodionov commented
У фильтра Авиакомпании нет креста сброса

2018-03-13 06:45 UTC, imevro requested changes

2018-03-13 06:45 UTC, evgenyrodionov commented on src/Common/DatePicker.js
> +            {to && (
зачем дейтпикеру знать о to или from?

2018-03-13 06:45 UTC, evgenyrodionov commented on src/Common/DatePicker.js
> +            {to && (
если это common компонент

2018-03-13 06:45 UTC, evgenyrodionov commented on src/Common/DepartAndArrival.js
> +        isOpen: false,
а зачем смешивать бизнес-логику и отображение на экране?

2018-03-13 06:45 UTC, evgenyrodionov commented on src/Search/Filter/TravelTime.js
> +  handleFromChange = (value) => {
две функции друг друга дублируют по сути

2018-03-15 16:24 UTC, SmogHard commented
https://build-pgdaaerjbv.now.sh/

2018-08-20 07:23 UTC, merged